name: "GitHub Actions Weather Bot"

on:
  push:
  schedule:
    - cron: "0 7 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install Node.js"
        uses: actions/setup-node@v1
      - name: "Install NPM dependencies"
        run: npm install
      - name: "Run code"
        run: npm start
      env:
        OPEN_WEATHER_API_TOKEN: ${{ secrets.OPEN_WEATHER_API_TOKEN }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
